$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
type: command

display_name: promptda_dpttrain_zerocnninit_higherlr_randomprior_easy_normalizedprior_randomscale
experiment_name: train_sparse_da


command: >
  bash -c "python train_promptda.py
  --pretrained-from=${{inputs.weights}}
  --relative-path=${{inputs.data}}
  --save-path=./outputs
  --bs=8
  --lr=0.00005 
  --epochs=30
  --save-model=0
  --invert-prior=0
  --normalize-prior=1
  --add-mask=0
  --l1-loss=1"
#changed default lr = 0.000005 
code: ..

inputs:
  data:
    type: uri_folder
    # use registered data asset by name:version (or set a direct azureml:// path)
    path: azureml:Hypersim:1
    mode: ro_mount

  weights:
    type: uri_folder
    # use registered data asset by name:version (or set a direct azureml:// path)
    path: azureml:depth_anything_weights:1
    mode: ro_mount

outputs:
  model_dir:
    type: uri_folder

environment: azureml:diffusion-finetune:10
compute: mashhood-alvi-gpu2